[package]
name = "arcpack-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.28"
lazy_static = "1.5.0"

[dependencies.simple_logger]
default-features = false
features = ["colors", "threads", "nightly", "stderr"]
version = "5.0.0"
